### ISSUE TITLE
Split "Advanced functions" into more granular lessons

### ISSUE THREAD

**Issue by ostephens** [data-lessons/library-openrefine-DEPRECATED#16]
Suggest:
1. Retrieving data from another source
2. Introduction to Reconciliation
3. Using OpenRefine Extensions

**Comment by weaverbel** [comment]
@ostephens Have also had people wanting to know how to combine two different datasets - is that covered anywhere?

**Comment by ostephens** [comment]
It depends what you mean. Advanced Functions covers looking up data from a remote data source and bringing it into your own data set in two ways - that is using lookup by URL and using reconciliation. What isn't covered in any detail is the 'cross' function which allows you to look up data from another OpenRefine project (this is mentioned but not demonstrated)
