### ISSUE TITLE
NER Extension

### ISSUE THREAD

**Issue by ccronje** [data-lessons/library-openrefine-DEPRECATED#2]
In reference to the NER demo issue logged in the Shell repo https://github.com/data-lessons/library-shell/issues/8 - I wonder if this NER Extension https://github.com/RubenVerborgh/Refine-NER-Extension could be a source for a NER demo in the advanced OpenRefine lesson? https://github.com/data-lessons/library-openrefine/blob/master/lesson-materials/Advanced-OpenRefine-functions.md

**Comment by ccronje** [comment]
Maybe this could be added to Extensions in http://data-lessons.github.io/library-openrefine/05-advance-functions/? Is it of interest?

**Comment by drjwbaker** [comment]
It is there really to demonstrate the other things can be done with the shell than just cd around, ls directories, and grep files: that is, fire up complex software (R, NER stuff, et cetera). Perhaps that is just as well explained as done here.

@ostephens: do you have an existing NER OpenRefine demo that could be slotted into that lesson? Perhaps as homework?

**Comment by ostephens** [comment]
@drjwbaker I don't have any NER in OR demo/exercises at the moment I'm afraid

**Comment by drjwbaker** [comment]
@ostephens Okay. I'll have a think.

**Comment by remerjohnson** [comment]
The makers of that extension have a mini-lesson. It obviously stops short, but at least gets you started. 
http://freeyourmetadata.org/named-entity-extraction/

**Comment by drjwbaker** [comment]
Thanks @remerjohnson!

**Comment by ccronje** [comment]
Ok to close this now it's referenced in https://github.com/data-lessons/library-openrefine/issues/65?
