### ISSUE TITLE
Create a handout for learners

### ISSUE THREAD

**Issue by ccronje** [data-lessons/library-openrefine-DEPRECATED#60]
Referencing discussion https://github.com/data-lessons/library-openrefine/issues/54#issuecomment-297873585 - learners do like to have a handout by their side during a workshop. Not sure where this should live in the repo.

**Comment by drjwbaker** [comment]
@ccronje I think this is a more general point. I use a handout for the shell lesson but don't have anywhere obvious to put it within the template.

So alongside developing specific handouts for specific lessons like this, shall we make handouts and their locations in the repos/sites a general sprint task? If we do this, we also need to consider writing up a workflow for turning a .md handout doc into something printable (so .docx or .pdf). I use pandoc http://pandoc.org/ but I'm sure there are less computational options out there!

**Comment by weaverbel** [comment]
+1 to making this a sprint task @ccronje @drjwbaker. I think pandoc is OK - I've used it on Linux and Windows - as long as we give clear instructions, that is OK. This may well be a task librarians would want to do/feel comfortable with. If we think it's a go, I'll add it to the README/CONTRIBUTING files.

**Comment by drjwbaker** [comment]
Thanks @weaverbel. I'd encourage any workflow we use to also offer a GUI and/or web based solution for converting .md to presentation formats, for example http://dillinger.io/

I've opened an issue at https://github.com/data-lessons/librarycarpentry/issues/30 @ccronje: this doesn't supersede this issue, as this is about a handout for the Refine lesson; the other issue is about making a place for lesson handouts and a workflow for conversion.

**Comment by ostephens** [comment]
Best solution IMO would have the handout build from the lessons at the same time as the html site? Am I being over ambitious?

**Comment by drjwbaker** [comment]
Probably :) I was just thinking of a handout as a flat document that lives in the repo and contained key reference materials for the lesson. So no more than 2 sides of A4. The highlights if you will. This should limit having to manage handouts too much as lessons evolve (my shell one is basically unchanged since the first time I taught shell).

**Comment by drjwbaker** [comment]
On this, see feedback on the recent Pittsburgh workshop at http://pad.software-carpentry.org/2017-05-18-pitt I used a handout for Shell and seem to have set a precedent! Note that handout I use (attached) is a reference guide rather than a step by step guide to the lesson. This may not work for Refine, but having just taught it I'm sure @jt14den will have some comments on what could work [LibCarp-Pittsburgh-handout.pdf](https://github.com/data-lessons/library-openrefine/files/1018108/LibCarp-Pittsburgh-handout.pdf)

**Comment by jt14den** [comment]
@drjwbaker, thanks for putting up the feedback. I def. liked your use of a handout in class. I'm wondering if we can use reformulated keypoints in the template as bullets for a handout?  Check out the shell reference pages for SWC unix: https://swcarpentry.github.io/shell-novice/reference/. Each episode's key points will populate the reference page for the lesson. We are currently missing a `reference.md` in the repo. If we put one in it, it would autogenerate one and build a menu item under the `extras` menu. This would be a nice way to reinforce what we think is important in each lesson.

**Comment by drjwbaker** [comment]
I like the idea of using `reference.md`. I don't like the idea of going into quite as much detail as the SWC example.

**Comment by jt14den** [comment]
I agree, I think the key points should be in the 7+-2 range or even 5+-2.

**Comment by drjwbaker** [comment]
@jt14den Sadly putting regex in the keypoints section of a lesson breaks the header. So I've just done this http://data-lessons.github.io/library-data-intro/reference/ instead for the intro lesson.

**Comment by drjwbaker** [comment]
See https://github.com/data-lessons/librarycarpentry/issues/30 for how to manage this once you do it :)

**Comment by drjwbaker** [comment]
When you get on this, see how http://data-lessons.github.io/library-data-intro/reference/ handles it for reference.

**Comment by drjwbaker** [comment]
We have a request for a workshop in Italy in September. The workshop will be lead in English with Italian helpers. To make this work they are asking for there to be a handout in English that can be translated into Italian.

Maintainers @ostephens @ccronje @pitviper6: I see you've been doing lots of this already. Do you think there are more work to be done and if so any chance this work can be done by mid August so they can get the translation done for September?

I suspect having stable and detailed handouts is a good model for extending out reach to librarians who don't work in English (translating everything is not something every workshop can handle).

**Comment by drjwbaker** [comment]
Further to the above, maintainers @ccronje @ostephens : I'm running a LC workhop in Padua with @danmichaelo in 14-15 September. They've asked if we can get the handouts for the lessons in place so they can translate them for the workshop (they want to translate the handouts only, not the lessons!). This is one of the lessons we'll use. Any chance you have something we can use for this that I can give them this week? (w/c 31 July) If not, could you give me a timescale I can pass on please?

**Comment by weaverbel** [comment]
I have created an OR handout that I use myself to teach it - it is a very cut down version to help me teach it without wading through a lot of distracting text. I can share that @drjwbaker if you want it.

**Comment by drjwbaker** [comment]
Seen as I've never taught Refine, that would be super useful. Are you happy to upload here?

**Comment by weaverbel** [comment]
It's a  Word doc so I I might just email it to you @drjwbaker
