### ISSUE TITLE
Add exercise to demonstrate 'cross' function

### ISSUE THREAD

**Issue by ccronje** [data-lessons/library-openrefine-DEPRECATED#61]
Create an example for 'Using the ‘cross’ function to lookup data in other OpenRefine projects'

Originally discussed https://github.com/data-lessons/library-openrefine/issues/48#issuecomment-253008018

**Comment by ccronje** [comment]
A common library problem is looking for title overlaps between vendors. I've been playing around with the cross function to try see how it works.

Using the lesson's data I created two identical projects.
 
1. In Project 1, on the ISSNs column I added a column based on this column using:
`cell.cross("Project 2", "ISSNs")[0].cells["Citation"].value`
This seems to work fine.
2. In Project 2 I deleted the first 5 cells in the ISSNs column. This worked as well - it picked up the row's Citation if there is an ISSN match further down.
3. In Project 2 I deleted the first 5 rows with the same results as test 2, as expected.
4. In Project 2 I did an a-z sort on the Authors column to rearrange the ISSNs and it no longer matched correctly. It behaves as though the rows in Project 2 are still in original order but brings over the Citation for a different ISSN.

Do the 'key' columns' rows have to be in the same sort order?

**Comment by ostephens** [comment]
Hi @ccronje 

Order doesn't matter when using cross function.

At the moment your cross expression `cell.cross("Project 2", "ISSNs")[0].cells["Citation"].value` just finds the first match. The way you use the 'cross' expression might depend on exactly what you are trying to do, but generally I wouldn't just drop additional matches unless I was really confident this was OK.

If I want to know 'are there any matches' or 'how many matches are there' I'd use:
`cell.cross("Project 2", "ISSNs").length()`or `cell.cross("Project 2", "ISSNs").length() > 0` - often as a Custom text facet

If I want to find matches, I'd tend to preserve all the matches using something like
`forEach(cell.cross("Project 2", "ISSNs"),r,r.cells["Citation"].value).join("|")`
to give me a pipe-joined list of the matches. I use this even if I only expect one match to be found - and then do a text filter on the data I've retrieved to find a pipe character - that alerts me to any instances where multiple matches have been found.

The problem with using cross to do title overlaps is that it goes only one way at a time - so to get the full picture you have to look at Project 1 and see if it has matches in Project 2, and then at Project 2 to see if it has matches in Project 1 - which is a bit tiresome. I wrote a blog post a few years ago where I tackled a similar problem in OpenRefine http://www.meanboyfriend.com/overdue_ideas/2012/11/using-open-refine-for-e-journal-data/

**Comment by ccronje** [comment]
Thanks @ostephens this is really helpful. I didn't mean to stop at the first match so thanks for pointing that out. The blog post describes the type of things we're trying to do in e-resource management as well. Coverage seems to be the hardest part to unravel. Fingerprinting the title is an interesting approach!
