### ISSUE TITLE
Discuss & develop an Advanced OpenRefine lesson

### ISSUE THREAD

**Issue by ccronje** [data-lessons/library-openrefine-DEPRECATED#65]
Some ideas:

1. Advanced GREL examples (see discussion https://github.com/data-lessons/library-openrefine/issues/14#issuecomment-223933396)
2. Build on examples and topics in the advanced episode http://data-lessons.github.io/library-openrefine/05-advance-functions/
3. More API examples using GREL to pick apart the XML/JSON
4. Named entity extraction (see discussion https://github.com/data-lessons/library-openrefine/issues/2#issuecomment-235342275)

**Comment by ostephens** [comment]
Another idea:
5. using Jython to do things that are hard/impossible in GREL

**Comment by ostephens** [comment]
Suggest we move this discussion to a Etherpad to give us a bit more of a collaborative place to discuss syllabus for Advanced OR lesson. Have setup this at http://pad.software-carpentry.org/library-advanced-or

**Comment by ccronje** [comment]
Relevant to this discussion: https://github.com/data-lessons/library-openrefine/issues/86
