### ISSUE TITLE
Episode 6: Extend with examples

### ISSUE THREAD

**Issue by ostephens** [data-lessons/library-openrefine-DEPRECATED#97]
The re-worked episodes structure has left this episode rather thin.

It needs at least some exercises added in. Potentially it could be well served by some additional content but not sure what.

Please add Exercises as priority, and discuss potential additional content in this issue

**Comment by ccronje** [comment]
@ostephens would this a good place to add exercises demonstrating:
1. Splitting/joining columns
2. Cross function (vlookup type functionality)
What do you think? It's deeper in the lesson so tempted to dive in rather than skim surface.

**Comment by ostephens** [comment]
+1 for Splitting/Joining columns
Possibly Cross needs to be after 'Transforms' have been introduced more generally. Essentially everything up until this point in the lesson is 'point and click' functions. It's only when you go to Basic Functions V that you start working with GREL - this was a deliberate structure when I first wrote the material, and I think it works still.

So Definitely on using the Split cols function
Possibly Transpose?

I'm in favour of avoiding Cross until GREL has been introduced later
